apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: us-east-1a
spec: 
  securityGroups: 
    - sg-0249467e33a2ca67d
  subnet: subnet-0b76b5b50b23149c0

---

apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: us-east-1b
spec: 
  securityGroups: 
    - sg-0249467e33a2ca67d
  subnet: subnet-00faea1d9b907ce1e

---

apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: us-east-1c
spec: 
  securityGroups: 
    - sg-0249467e33a2ca67d
  subnet: subnet-0e67845eb6b51025f

